using System;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSDemo1.db
{
    public class SupplierBase
    {
        internal string image;
#pragma warning disable IDE0052 // Remove unread private members
        private readonly screen.Suppliers.dd P = new screen.Suppliers.dd();
#pragma warning restore IDE0052 // Remove unread private members

        public int id { get; set; }
        public string Name { get; set; }
        public string address { get; set; }
        public string Notes { get; set; }
        public string Pone { get; set; }
        public string Company { get; set; }
        public string email { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string Image { get; set; }
    }
}